//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work_SightOfOneCity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.AuthorOfSight = new HashSet<AuthorOfSight>();
        }
        public Author(string Family, string Name, string Patronymic, bool Gender, short Year)
        {
            this.FamilyAuthor = Family;
            this.NameAuthor = Name;
            this.PatronymicAuthor = Patronymic;
            this.Gender = Gender;
            this.DateBirthday = Year;
        }
    
        public long ID { get; set; }
        public string FamilyAuthor { get; set; }
        public string NameAuthor { get; set; }
        public string PatronymicAuthor { get; set; }
        public bool Gender { get; set; }
        public short DateBirthday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorOfSight> AuthorOfSight { get; set; }
    }
}
