//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work_SightOfOneCity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SightOfOneCityEntities : DbContext
    {
        public SightOfOneCityEntities()
            : base("name=SightOfOneCityEntities")
        {
        }

        public SightOfOneCityEntities(string connection)
            : base(connection)
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<AuthorOfSight> AuthorOfSight { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<KindOfTransport> KindOfTransport { get; set; }
        public virtual DbSet<Sight> Sight { get; set; }
        public virtual DbSet<StatusSight> StatusSight { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
        public virtual DbSet<TransportStop> TransportStop { get; set; }
        public virtual DbSet<TransportToSight> TransportToSight { get; set; }
        public virtual DbSet<WorkDays> WorkDays { get; set; }
        public virtual DbSet<View_Full> View_Full { get; set; }
    }
}
