//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work_SightOfOneCity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportToSight
    {
        public long SightID { get; set; }
        public long TransportID { get; set; }
        public bool Final { get; set; }
        public bool Special { get; set; }
    
        public virtual Sight Sight { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
