//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work_SightOfOneCity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Full
    {
        public string NameSight { get; set; }
        public string NameCategory { get; set; }
        public string NameStatus { get; set; }
        public string FamilyAuthor { get; set; }
        public string NameAuthor { get; set; }
        public string PatronymicAuthor { get; set; }
    }
}
